language: node_js
node_js:
   - "12.*"

branches:
  only:
  - main
  - dev

after_success: npm run cov

cache:
  directories:
    - node_modules # NPM packages

notifications:
  email: false

sudo: false
